name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '7.4'
            extensions: mbstring, intl, cURL, Zip # Add any extensions you need
    
        - name: Download php2exe
          run: |
            Invoke-WebRequest -Uri "https://www.php2exe.com/download/php2exe-1.0.0.zip" -OutFile "php2exe.zip"
            Expand-Archive -Path "php2exe.zip" -DestinationPath "."
    
        - name: Build EXE
          run: |
            ./php2exe-1.0.0/php2exe TraktExtract.php -o traktextract.exe
    
        - name: Upload artifact
          uses: actions/upload-artifact@v2
          with:
            name: traktextract.exe
            path: traktextract.exe